# Generated by Django 4.1.7 on 2023-03-30 19:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_client_favourites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0002_alter_specification_unique_together"),
        ("favourites", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavouritesItem",
            new_name="Item",
        ),
        migrations.RenameModel(
            old_name="Favourites",
            new_name="List",
        ),
    ]
