# Generated by Django 4.1.7 on 2023-03-30 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_client_favourites"),
        ("favourites", "0002_rename_favouritesitem_item_rename_favourites_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="favourites_info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="list",
            name="user",
        ),
        migrations.AlterField(
            model_name="item",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="favourites.info",
            ),
        ),
    ]
