# Generated by Django 4.2.1 on 2023-05-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("favourites", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourites_info",
                to="users.client",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("cart", "variant")},
        ),
    ]
