# Generated by Django 4.2.1 on 2023-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="2b515c672a3f47fd8fd9119118c7a75e",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
