# Generated by Django 4.2.1 on 2023-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="a3709b17db9344d8b772b578556435db",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
