# Generated by Django 4.2.1 on 2023-05-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0004_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="dad26d6832634fa3808a56166198c3a6",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
