# Generated by Django 4.2.1 on 2023-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0004_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="07f720fdf6b44c2c9eb29ab968cac769",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
