# Generated by Django 4.2.1 on 2023-05-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0005_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="bc7680dfa0464a588eb60ddc2212bf24",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
