# Generated by Django 4.2.1 on 2023-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0006_alter_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.UUIDField(default='03ab55893cb545f9a5ab32c5430999af', editable=False, primary_key=True, serialize=False),
        ),
    ]
