# Generated by Django 4.2.1 on 2023-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0006_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="76bb8ed04e9f43dcbc16e5140f87941d",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
