# Generated by Django 4.2.1 on 2023-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0007_alter_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.UUIDField(default='d32f3d148b454ddf9ae3a3fa97d784e7', editable=False, primary_key=True, serialize=False),
        ),
    ]
