# Generated by Django 4.2.1 on 2023-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0008_alter_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.UUIDField(default='257b5d32b1964ee68f5a8d1b2b4daeff', editable=False, primary_key=True, serialize=False),
        ),
    ]
