# Generated by Django 4.2.1 on 2023-05-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0009_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="fb3fce0816ac42778513e3618edcbd4b",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
