# Generated by Django 4.2.1 on 2023-05-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0009_alter_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.UUIDField(default='cba8cc2af7de49cf8d4a3a4426cda992', editable=False, primary_key=True, serialize=False),
        ),
    ]
