# Generated by Django 4.2.1 on 2023-05-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0010_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="44601c44589d49cea3f9bfb1af92d9ff",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
