# Generated by Django 4.2.1 on 2023-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0010_alter_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.UUIDField(default='1229a7d161794d81a9cf1c22ec4e7368', editable=False, primary_key=True, serialize=False),
        ),
    ]
