# Generated by Django 4.2.1 on 2023-05-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0011_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="0e537674e8f7406da2a9199d959b1e3e",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
