# Generated by Django 4.2.1 on 2023-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0012_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="299313e52f9c4c2fa935f29f97acb3f8",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
