# Generated by Django 4.2.1 on 2023-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0012_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="6054c710800d4f61b5f1ac24abeae2f3",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
