# Generated by Django 4.2.1 on 2023-05-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0013_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="c2da8b77bcfe4d5ea1adafe26f7cd035",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
