# Generated by Django 4.2.1 on 2023-05-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0014_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="b0e07838de2742f492e0a4668873fb12",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
