# Generated by Django 4.2.1 on 2023-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0015_alter_info_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.UUIDField(default='b8e7f3aff9144faa875791961790ab6a', editable=False, primary_key=True, serialize=False),
        ),
    ]
