# Generated by Django 4.2.1 on 2023-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0015_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="ae6c24d5108142a38c16b17bf636a919",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
