# Generated by Django 4.2.1 on 2023-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0017_alter_info_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="id",
            field=models.UUIDField(
                default="a2ba658c62ce4d4bbb5ea632d3ae2960",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
