# Generated by Django 4.1.7 on 2023-03-17 00:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseInfo",
            fields=[
                (
                    "ean",
                    models.CharField(
                        editable=False, max_length=14, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("price_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "filename",
                    models.CharField(
                        editable=False, max_length=21, primary_key=True, serialize=False
                    ),
                ),
                ("media_type", models.CharField(max_length=4)),
                ("pos", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "sku",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
                ("mediafiles_hash", models.CharField(max_length=64)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "info",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Variant",
                        to="products.baseinfo",
                    ),
                ),
                ("media", models.ManyToManyField(to="products.media")),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "variant_id",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="products.variant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("value", models.TextField()),
            ],
            options={
                "unique_together": {("key", "value")},
            },
        ),
        migrations.AddField(
            model_name="media",
            name="variant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Variant_image",
                to="products.variant",
            ),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logo_image",
                        to="products.media",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="baseinfo",
            name="brand",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_baseInfo",
                to="products.brand",
            ),
        ),
        migrations.AddField(
            model_name="baseinfo",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_baseInfo",
                to="products.category",
            ),
        ),
        migrations.AddField(
            model_name="baseinfo",
            name="specifications",
            field=models.ManyToManyField(to="products.specification"),
        ),
    ]
