# Generated by Django 4.1.7 on 2023-03-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("name", models.CharField(max_length=128)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("name", models.CharField(max_length=128)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=512)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                ("name", models.CharField(max_length=128)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
