# Generated by Django 4.2.1 on 2023-05-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default="fe6ae2a6472c46c48b1d5c974db663ec",
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "CREATED"),
                            ("Payment Pending", "PAYMENT_PENDING"),
                            ("Payment Confirmed", "PAYMENT_CONFIRMED"),
                            ("Shipped", "SHIPPED"),
                            ("Delivered", "DELIVERED"),
                            ("Cancelled", "CANCELLED"),
                        ],
                        default="Created",
                        max_length=20,
                    ),
                ),
                ("payment_info", models.TextField(null=True)),
                ("shipped_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_items",
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
