# Generated by Django 4.2 on 2023-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="a7ef818a49ce46c286fb8c618a1143cf",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
