# Generated by Django 4.2 on 2023-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="4c79274b2da947d895b24d6741cbe831",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
