# Generated by Django 4.2.1 on 2023-05-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="91b0f852512f4fc295c1eb1f210c0c5f",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
