# Generated by Django 4.2 on 2023-05-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="794ee2da6cf64df8a7a67bf88dd0ac98",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
