# Generated by Django 4.2.1 on 2023-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="5cc2056bd6964206b390e81751c1cff7",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
