# Generated by Django 4.2.1 on 2023-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='bc682cd0f78342718740ef4b9a60c7b9', editable=False, primary_key=True, serialize=False),
        ),
    ]
