# Generated by Django 4.2.1 on 2023-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='b14ab566d0e6493cafe5246da5adb4f9', editable=False, primary_key=True, serialize=False),
        ),
    ]
