# Generated by Django 4.2.1 on 2023-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="21a8ee1acba2475ca957b5121e5d46d8",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
