# Generated by Django 4.2.1 on 2023-05-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="19edb6d0f6b24eb88404b35236cb8866",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
