# Generated by Django 4.2.1 on 2023-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='87b6033e171b45d5bdbf36fe06150c87', editable=False, primary_key=True, serialize=False),
        ),
    ]
