# Generated by Django 4.2.1 on 2023-05-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="b0bbac04151149d8bf73e8c8a3007943",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
