# Generated by Django 4.2.1 on 2023-05-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='765133b6f5b74738b68d24f1ee5ab881', editable=False, primary_key=True, serialize=False),
        ),
    ]
