# Generated by Django 4.2.1 on 2023-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='78a279d118f2480bb4fe53fa229770cb', editable=False, primary_key=True, serialize=False),
        ),
    ]
