# Generated by Django 4.2.1 on 2023-05-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="fe48f547aeaf437cab4dfbb8ce1b9492",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
