# Generated by Django 4.2.1 on 2023-05-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="b0f7e0b0ee3843fc8683ed5906b4d7d0",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
