# Generated by Django 4.2.1 on 2023-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="1d1b400d560f448a90f95dd99fc66cd6",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
