# Generated by Django 4.2.1 on 2023-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="91cc9c1362a44575a9e7e36aaff5e67c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
