# Generated by Django 4.2.1 on 2023-05-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="include_nif",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="59da1432450646c88a0b83c10cff38c6",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
