# Generated by Django 4.2.1 on 2023-05-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="faefea9681eb41138caef8d8f49d0a0c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
