# Generated by Django 4.2.1 on 2023-05-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_order_include_nif_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_option",
            field=models.CharField(
                choices=[("CTT", "CTT"), ("DHL", "DHL"), ("UPS", "UPS")],
                default="CTT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="141a6bae9c0049d98fef1dff0bc1230d",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
