# Generated by Django 4.2.1 on 2023-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_order_delivery_option_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="a791c39624d34abdbbe3d9200e4b68ed",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
