# Generated by Django 4.2.1 on 2023-05-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='b824e6af496b42a48e06bdbe1675f68f', editable=False, primary_key=True, serialize=False),
        ),
    ]
