# Generated by Django 4.2.1 on 2023-05-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordereditem",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="5c88b2d2a5d24f9987f8cd4d727615bc",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
