# Generated by Django 4.2.1 on 2023-05-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="cf6dc5e8c3d147daba26e742f02198e4",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
