# Generated by Django 4.2.1 on 2023-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0017_ordereditem_total_cost_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default="ccd8f2095bac4120a46db872bd2e688c",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
