# Generated by Django 4.1.7 on 2023-03-23 00:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import users.validators
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="apartment_number",
        ),
        migrations.RemoveField(
            model_name="client",
            name="city",
        ),
        migrations.RemoveField(
            model_name="client",
            name="country",
        ),
        migrations.RemoveField(
            model_name="client",
            name="house_number",
        ),
        migrations.RemoveField(
            model_name="client",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="client",
            name="street",
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cardholder_name", models.CharField(max_length=255)),
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        validators=[users.validators.validate_card_number],
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                (
                    "expiry_month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "expiry_year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(2023)]
                    ),
                ),
                ("cvv", models.CharField(max_length=4)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to="users.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+[a-zA-Z\\s\\-]*$",
                                message="House number can only contain digits, letters, spaces, and hyphens.",
                            )
                        ],
                    ),
                ),
                (
                    "apartment_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{5}(-\\d{4})?$",
                                message="Postal code must be in the format '12345' or '12345-6789'.",
                            )
                        ],
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.CITIES_CITY_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.client"
                    ),
                ),
            ],
        ),
    ]
