# Generated by Django 4.2.1 on 2023-05-13 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("favourites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="favourites",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="favourites.info",
            ),
        ),
    ]
