# Generated by Django 4.2 on 2023-04-24 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("favourites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="favourites",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="favourites.info",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.client"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={
                (
                    "client",
                    "country",
                    "city",
                    "street",
                    "house_number",
                    "apartment_number",
                    "postal_code",
                )
            },
        ),
    ]
