# Generated by Django 4.1.7 on 2023-03-23 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ("users", "0002_remove_client_apartment_number_remove_client_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.CITIES_COUNTRY_MODEL,
            ),
        ),
    ]
