# Generated by Django 4.2 on 2023-05-12 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default="fe9f89f0ed1b4a4b97e979820e6dec95",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9\\s\\-]*$",
                        message="Postal code can only contain digits, letters, spaces, and hyphens.",
                    )
                ],
            ),
        ),
    ]
