# Generated by Django 4.2 on 2023-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.UUIDField(
                default="9e50c588dc4c4c778c77bb9b6bf3b2e2",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
