# Generated by Django 4.1.7 on 2023-03-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_address_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="client",
            name="receive_news",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="nif",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
