# Generated by Django 4.1.7 on 2023-03-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("favourites", "0003_info_remove_list_user_alter_item_cart"),
        ("users", "0003_alter_client_favourites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="favourites",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="favourites.info",
            ),
        ),
    ]
