# Generated by Django 4.1.7 on 2023-03-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_admin_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
