# Generated by Django 4.1.7 on 2023-03-25 01:48

import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("users", "0007_alter_admin_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "logentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="admin.logentry",
                    ),
                ),
                ("_user_id", models.UUIDField()),
            ],
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AlterField(
            model_name="admin",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
