# Generated by Django 4.1.7 on 2023-03-25 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_logentry_alter_admin_is_superuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogEntry",
        ),
    ]
