# Generated by Django 4.1.7 on 2023-03-25 02:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ("users", "0009_delete_logentry"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={
                (
                    "client",
                    "country",
                    "city",
                    "street",
                    "house_number",
                    "apartment_number",
                    "postal_code",
                )
            },
        ),
    ]
