# Generated by Django 4.1.7 on 2023-03-25 15:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_address_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.AlterModelManagers(
            name="admin",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="client",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="admin",
            name="receive_news",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("N", "Prefer not to say"),
                ],
                default="O",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="EnterpriseClient",
        ),
    ]
