# Generated by Django 4.1.7 on 2023-03-30 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="specification",
            unique_together=set(),
        ),
    ]
