# Generated by Django 4.2.1 on 2023-05-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="supply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supply_units",
                to="supply.info",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="variant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="product.variant",
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type",
                to="product.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category",
                to="product.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="specification",
            constraint=models.UniqueConstraint(
                fields=("key", "value"), name="unique_key_value"
            ),
        ),
    ]
