# Generated by Django 4.1.7 on 2023-03-16 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specification",
            options={"ordering": ["-name"]},
        ),
    ]
