# Generated by Django 4.1.7 on 2023-03-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="hash",
            field=models.CharField(default=" ", max_length=64),
        ),
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
