# Generated by Django 4.2 on 2023-05-01 21:06

import django.core.validators
from django.db import migrations, models
import product.models.variant


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="_is_default",
        ),
        migrations.AddField(
            model_name="variant",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                upload_to="categories/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "svg"],
                        message="File format not supported.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="_altered_specifications",
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="sku",
            field=models.CharField(
                default=product.models.variant.generate_unique_sku,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
