# Generated by Django 4.2.1 on 2023-05-14 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_unit_supply_alter_unit_variant_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Option",
        ),
    ]
