# Generated by Django 4.2.1 on 2023-05-25 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_variant_mediafiles_hash_alter_variant_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="mediafiles_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="variant",
            name="sku",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
