# Generated by Django 4.2.1 on 2023-05-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_variant_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseinfo",
            name="details",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="ean",
            field=models.CharField(max_length=14),
        ),
    ]
